public  enum Category {
    ALCOHOL,
    CANNED_GOODS,
    FROZEN_FOODS,
    MEAT_AND_SEAFOODS,
    TOBACCO,
    BREAD_AND_BAKERY,
    DAIRY_EGGS_AND_CHEESE,
    BEVERAGES,
    FRUITS_AND_VEGETABLES

}
